uint32 min_exposure_time_us
uint32 max_exposure_time_us
uint32 min_gain_x1024
uint32 max_gain_x1024
---
bool success
string message
uint32 min_exposure_time_us
uint32 max_exposure_time_us
uint32 effective_max_exposure_time_us
uint32 min_gain_x1024
uint32 max_gain_x1024
